### ISSUE TITLE
Options not working

### ISSUE THREAD

**Issue by aintea4** [marzeq/drevo-calibur-2-linux-fnkeys#2]
The script fixed the keys, but now by doing FN+F12, i can't up the volume, and same for any FN+F#

**Comment by marzeq** [comment]
This is an unfortunate by-product of this method. 

This is because you can either use the FN modifier key to do media controls or to do function keys, you can't do both at the same time.

You can setup a shortcut to have certain function keys work as your media controls in your DE/WM settings, this is my only solution.

If you prefer to have them working like before, you can revert it by running:

```
echo 1 | sudo tee /sys/module/hid_apple/parameters/fnmode

echo options hid_apple fnmode=1 | sudo tee -a /etc/modprobe.d/hid_apple.conf

# update your initial ram disk using the appropriate command for your distro

# Arch:
sudo mkinitcpio -P
# Debian/Ubuntu + related:
sudo update-initramfs -u
# Fedora:
sudo dracut --regenerate-all --force
```
